version: '3.8'
services:
  # user-service:
  #   build: ./backend/user-service
  #   ports:
  #     - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
  #   environment:
  #     - MONGO_URI=mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${USER_DB}
  #   # depends_on:
  #   #   - mongo

  reservation-service:
    build: ./backend/reservation-service
    ports:
      - "${RESERVATION_SERVICE_PORT}:${RESERVATION_SERVICE_PORT}"
    environment:
      - MONGO_URI=mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${RESERVATION_DB}
    # depends_on:
    #   - mongo

  food-service:
    build: ./backend/food-service
    ports:
      - "${FOOD_SERVICE_PORT}:${FOOD_SERVICE_PORT}"
    environment:
      - MONGO_URI=mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${FOOD_DB}
    # depends_on:
    #   - mongo

  order-service:
    build: ./backend/order-service
    ports:
      - "${ORDER_SERVICE_PORT}:${ORDER_SERVICE_PORT}"
    environment:
      - MONGO_URI=mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${ORDER_DB}
    # depends_on:
    #   - mongo

  # table-service:
  #   build: ./backend/table-service
  #   ports:
  #     - "${TABLE_SERVICE_PORT}:${TABLE_SERVICE_PORT}"
  #   environment:
  #     - MONGO_URI=mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${TABLE_DB}
  #   # depends_on:
  #   #   - mongo

  payment-service:
    build: ./backend/payment-service
    ports:
      - "${PAYMENT_SERVICE_PORT}:${PAYMENT_SERVICE_PORT}"
    environment:
      - MONGO_URI=mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${PAYMENT_DB}
    # depends_on:
    #   - mongo

  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "3000:3000"
    depends_on:
      # - user-service
      - reservation-service
      - food-service
      - order-service
      # - table-service
      - payment-service
    restart: unless-stopped

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "${FRONTEND_PORT}:${FRONTEND_PORT}"
  #   depends_on:
  #     - api-gateway 