services:
  user-service:
    build: ./backend/user-service
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    environment:
      - MONGO_URI=mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${USER_DB}
      - JWT_SECRET_KEY=your_jwt_secret_key_here
      - JWT_EXPIRE_TIME=7d
      - NODE_ENV=development
    # depends_on:
    #   - mongo

  reservation-service:
    build: ./backend/reservation-service
    ports:
      - "${RESERVATION_SERVICE_PORT}:${RESERVATION_SERVICE_PORT}"
    environment:
      - MONGO_URI=mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${RESERVATION_DB}
      - USER_SERVICE_URL=http://user-service:3001
      - TABLE_SERVICE_URL=http://table-service:3005/api/v1
      - NODE_ENV=development
    # depends_on:
    #   - mongo

  food-service:
    build: ./backend/food-service
    ports:
      - "${FOOD_SERVICE_PORT}:${FOOD_SERVICE_PORT}"
    environment:
      - MONGO_URI=mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${FOOD_DB}
      - USER_SERVICE_URL=http://user-service:3001
      - NODE_ENV=development
    # depends_on:
    #   - mongo

  order-service:
    build: ./backend/order-service
    ports:
      - "${ORDER_SERVICE_PORT}:${ORDER_SERVICE_PORT}"
    environment:
      - MONGO_URI=mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${ORDER_DB}
      - USER_SERVICE_URL=http://user-service:3001
      - TABLE_SERVICE_URL=http://table-service:3005
      - RESERVATION_SERVICE_URL=http://reservation-service:3002
      - FOOD_SERVICE_URL=http://food-service:3003
      - NODE_ENV=development
    # depends_on:
    #   - mongo

  table-service:
    build: ./backend/table-service
    ports:
      - "${TABLE_SERVICE_PORT}:${TABLE_SERVICE_PORT}"
    environment:
      - MONGO_URI=mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${TABLE_DB}
      - USER_SERVICE_URL=http://user-service:3001
      - RESERVATION_SERVICE_URL=http://reservation-service:3002/api/v1
      - NODE_ENV=development
    # depends_on:
    #   - mongo

  payment-service:
    build: ./backend/payment-service
    ports:
      - "${PAYMENT_SERVICE_PORT}:${PAYMENT_SERVICE_PORT}"
    environment:
      - MONGODB_URI=mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${PAYMENT_DB}
      - USER_SERVICE_URL=http://user-service:3001
      - ORDER_SERVICE_URL=http://order-service:3004
      - RESERVATION_SERVICE_URL=http://reservation-service:3002
    # depends_on:
    #   - mongo

  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - reservation-service
      - food-service
      - order-service
      - table-service
      - payment-service
    restart: unless-stopped

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "${FRONTEND_PORT}:${FRONTEND_PORT}"
  #   depends_on:
  #     - api-gateway 